version=0.1

# TODO - can we have a common place for parameters that are the same across environments

# About Key Parameters
#   resolve_s3 
#       Used for automatically creating an s3 bucket for packaging and deploying...this should be fine but if needed we can 
#       provide a named bucket using s3_bucket instead
#       https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-global.html
#   capabilities
#       Currently using CAPABILITY_IAM which means we aren't using custom named capabilites in IAM and we may need to revisit
#       https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html#API_CreateStack_RequestParameters
#   parameter_overrides
#       Using this to pass parameters to template.yml dynamically as part of deployment so we can vary them by environment

# Parameters for alpha application environment
[alpha.global.parameters]
region = "us-east-2"
stack_name = "sample-application-api-alpha"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "LamdaFunctionName=sample-application-api-alpha",
    "ESSecretName=alpha-es",
]
tags = "STAGE=\"alpha\" TYPE=\"backend-api\""

# Parameters for beta application environment
[beta.global.parameters]
region = "us-east-2"
stack_name = "sample-application-api-beta"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "LamdaFunctionName=sample-application-api-beta"
]
tags = "STAGE=\"beta\" TYPE=\"backend-api\""

# Parameters for qa application environment
[qa.global.parameters]
region = "us-east-2"
stack_name = "sample-application-api-qa"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "LamdaFunctionName=sample-application-api-qa"
]
tags = "STAGE=\"qa\" TYPE=\"backend-api\""

# Parameters for uat application environment
[uat.global.parameters]
region = "us-east-2"
stack_name = "sample-application-api-uat"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "LamdaFunctionName=sample-application-api-uat"
]
tags = "STAGE=\"uat\" TYPE=\"backend-api\""

# Parameters for prod application environment
[prod.global.parameters]
region = "us-east-2"
stack_name = "sample-application-api-prod"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "LamdaFunctionName=sample-application-api-prod"
]
tags = "STAGE=\"prod\" TYPE=\"backend-api\""