# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >
  sample-application

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 100
    Architectures:
    - arm64
    Environment:
      Variables:
        IS_OFFLINE: true
        NODE_DEV: DEV

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

Resources:
  SharedApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "ApiGatewayName=shared-gateway-{environment}"
      StageName: Staging

Outputs:
  SharedAWSApiGatewayRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref SharedApiGateway
    Export:
      Name: !Sub "{environment}-BasicAWSApiGateway-RestApiId"
  SharedAWSApiGatewayRootResourceId:
    Value: !GetAtt SharedApiGateway.RootResourceId
    Export:
      Name: !Sub "{environment}-BasicAWSApiGateway-RootResourceId"