#----------------------------------------------------------------------------------------------------------------------
# This workflow will build and test the application and should be called on EVERY commit
#----------------------------------------------------------------------------------------------------------------------
name: Build and Test

on:
  workflow_call:
    inputs:
      AWS-SECRETS-TO-PULL:
        type: string
        description: 
        required: false       
      AWS-REGION:
        type: string
        description:  Region to deploy to
        required: false
    secrets: 
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Clone ${{ github.repository }} repo to the runner
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Application
        run: yarn build

      - name: Lint Application
        run: yarn lint

      # - name: Configure AWS Credentials
      #   if: ${{ inputs.SECRETS-TO-PULL != ''}}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ inputs.AWS-REGION }}

      # # Pull secrets into environment variables
      # # For more see: https://github.com/aws-actions/aws-secretsmanager-get-secrets
      # - name: Read secrets from AWS Secrets Manager into environment variables
      #   if: ${{ inputs.SECRETS-TO-PULL != ''}}
      #   uses: aws-actions/aws-secretsmanager-get-secrets@v1
      #   with:
      #     secret-ids: |
      #       ${{ inputs.SECRETS-TO-PULL }}
      #     parse-json-secrets: true

      # - name: Execute Unit Tests
      #   run: yarn test