#----------------------------------------------------------------------------------------------------------------------
# This reusable workflow is intended to be called for each different deployment target with a environment input used 
# to set the environment which will determine the secrets pulled for deployment.
# It is based on information from the below link
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
#----------------------------------------------------------------------------------------------------------------------
name: Deploy Lambda

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
      region:
        type: string
        description:  region to deploy to
        required: true

jobs:
  deploy: 
    # name: Deploy ${{ inputs.environment }} 
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - run: echo Delpoying to ${{ inputs.environment }} environment in the ${{ inputs.region }} region
      # - name: Debugging Secrets to make sure the right version by environment is set
      #   run: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}| sed 's/./& /g'

      - name: Clone ${{ github.repository }} repo to the runner
        uses: actions/checkout@v3 #checkout repo to github/workspace

      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Build App Using SAM CLI
        run: sam build --use-container          

      # Potentially revisit this approach if something with sam build doesn't work out
      # - name: Download Build Outputs
      #   uses: actions/download-artifact@v3å
      #   with:
      #     name: dist

      # - name: List files in the repository
      #   run: ls ${{ github.workspace }}         