#----------------------------------------------------------------------------------------------------------------------
# This workflow should only execute when code is committed to beta which means it needs to be tested before going to
# the beta (integrated development environment) AND the alpha environment
#----------------------------------------------------------------------------------------------------------------------
name: Beta Pipeline

on: 
  push:
    branches:
      - 'beta'

jobs:

  build:
     uses: ./.github/workflows/build_yarn.yml

  deploy-beta: 
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      environment: beta
      region: us-east-2
    secrets: inherit # pass all secrets
    needs: [ build ]

  deploy-alpha:
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      environment: alpha
      region: us-east-2
    secrets: inherit # pass all secrets
    needs: [ build ]    