#----------------------------------------------------------------------------------------------------------------------
# This workflow will execute to build and test the application on commits to development branches
# It can optionally deploy to the alpha environment by prefixing your last commit comment with #alpha
#----------------------------------------------------------------------------------------------------------------------
name: Development Pipeline

on: 
  push:
    branches-ignore:
      - 'main'
      - 'beta'

jobs:

  build:
     uses: bogeorge/github_workflows/.github/workflows/build.yml

  deploy-alpha:
    if: ${{ startsWith(github.event.head_commit.message, '#alpha') }}
    uses: bogeorge/github_workflows/.github/workflows/deploy.yml
    with:
      environment: alpha
    needs: [ build ]