#----------------------------------------------------------------------------------------------------------------------
# This workflow will execute to build and test the application on commits to development branches
# It can optionally deploy to the alpha environment by prefixing your last commit comment with #alpha
#----------------------------------------------------------------------------------------------------------------------
name: Development Pipeline

on: 
  push:
    branches-ignore:
      - 'main'
      - 'beta'

jobs:

  # Why Do this?  
  # Well because Github is lame and doesn't seem to let us simple use env: at the workflow level and pass 
  # those variables into our jobs for example using the with: option to pass them to workflows
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      AWS_STACK_NAME: ${{ steps.init.outputs.AWS_STACK_NAME }}
    steps:
      - name: init
        run: |
          echo $AWS_STACK_NAME >> $GITHUB_OUTPUT

  build:
     #uses: bogeorge/github_workflows/.github/workflows/build_yarn.yml@v2.0
     uses: ./.github/workflows/build_yarn.yml

  deploy-alpha:
    # if: ${{ startsWith(github.event.head_commit.message, '#alpha') }}
    #uses: bogeorge/github_workflows/.github/workflows/deploy_lambda.yml@v2.0
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      app-environment: alpha
      aws-region: us-east-2
      aws-stack-name: ${{needs.env-setup.outputs.AWS_STACK_NAME}}
    secrets: inherit # pass all secrets
    needs: [ env-setup, build ]