#----------------------------------------------------------------------------------------------------------------------
# This workflow will execute to build and test the application on commits to development branches
# It can optionally deploy to the alpha environment/stage by prefixing your last commit comment with #alpha
#----------------------------------------------------------------------------------------------------------------------
name: Development Pipeline

on: 
  push:
    branches-ignore:
      - 'main'
      - 'beta'

jobs:

test-secrets-manager:
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ALPHA_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ALPHA_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Read secrets from AWS Secrets Manager into environment variables
      uses: abhilash1in/aws-secrets-manager-action@v2.1.0
      with:
        secrets: |
          alpha-es
        parse-json: true

    - name: Check if env variable is set after fetching secrets
      run: if [ -z ${alpha-es+x} ]; then echo "alpha-es is unset"; else echo "alpha-es is set to '$alpha-es'"; fi





  build:
     #uses: bogeorge/github_workflows/.github/workflows/build_yarn.yml@v2.0
     uses: ./.github/workflows/build_yarn.yml

  deploy-alpha:
    if: ${{ startsWith(github.event.head_commit.message, '#alpha') }}
    #uses: bogeorge/github_workflows/.github/workflows/deploy_lambda.yml@v2.0
    uses: ./.github/workflows/deploy_lambda.yml
    with:
      ENVIRONMENT-STAGE: alpha
      AWS-REGION: us-east-2    
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.ALPHA_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.ALPHA_AWS_SECRET_ACCESS_KEY }}
    needs: [ build ]